language: node_js

node_js:
  - "8.9"

notifications:
  slack:
    rooms:
      - creativeteam-network:p8YW1iPy1dVw84KkW7sLlOBH#general
      - creativeteam-network:p8YW1iPy1dVw84KkW7sLlOBH#now-ui
  # on_success: never # default: change
  # on_failure: always # default: always

sudo: required

addons:
  artifacts: true

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


before_script:
  - "npm install"
  - npm start &


script:
  - npm run e2e